name: libbad-zapple build check
run-name: ${{ github.actor }}
on: [pull_request, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - run: echo "Running on ${{ runner.os }} server hosted by GitHub"
      - run: echo "Branch ${{ github.ref }} from repository ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: make
      - run: echo "Status: ${{ job.status }}."
