name: libbad-zapple build check
run-name: ${{ github.actor }}
on: [pull_request, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - run: echo "Running on ${{ runner.os }} server hosted by GitHub"
      - run: echo "Branch ${{ github.ref }} from repository ${{ github.repository }}."
#      - name: install-catch2
#        run: sudo apt update && sudo apt install catch2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tests
        run: make run-test
      - run: echo "Status ${{ job.status }}."
